# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Stage 1: Build
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build the TypeScript code
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci && npm run build

# Stage 2: Runtime
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy production artifacts
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

ENV NODE_ENV=production

# Entry point for the MCP server
CMD ["node", "build/server.js"]
